---
  - name: Config Elk vm with docker
    hosts: elk
    remote_user: azureuser
    become: true
    tasks:

      - name: docker.io
        apt:
          force_apt_get: yes
          update_cache: yes
          name: docker.io
          state: present

      - name: Install pip3
        apt:
          force_apt_get: yes
          name: python3-pip
          state: present

      - name: Install Docker python module
        pip:
          name: docker
          state: present

      - name: Increase virtual memory
        command: sysctl -w vm.max_map_count_count= 262144

      - name: Use more memory
        sysctl:
          name: Increase virtual memory
          value: 1
          state: present
          reload: yes

      - name: download and launch a docker elk container
        docker_container:
          name: elk
          image: sebp/elk:761
          state: started
